### ISSUE TITLE
Not all bus collisions are recognized by DALI mon

### ISSUE THREAD

**Issue by twendtland** [SvenHaedrich/dali_mon#15]
While testing device address setup with `compare`, I noticed that dali_mon seems to miss out on some of the bus status messages. This can be reproduced by continuously sending 'compare'. a different tool (DALI monitor or even a Logic Analyser) will show collisions where dali_mon does not.

**Comment by SvenHaedrich** [comment]
I was able to reproduce the problem. The problem is located in my interface to the USB device. Expect a fix soon.

**Comment by SvenHaedrich** [comment]
Try the latest release v1.2.0 it should report all backframes, valid and trash-frames as well.
